version: '3.9'

services:
  mysql_container:
    image: mysqldb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/employee
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee
    ports:
      - "3306:3306"
    volumes:
      - mysql_docker:/var/lib/mysql

volumes:
  mysql_docker: