spring:
  datasource:
    url: jdbc:mysql://localhost:3307/employee
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Configuración de la aplicación
  jpa:
    hibernate:
      ddl-auto: update
  # Configuración de la seguridad
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER